version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: task-management-api-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: task-management-api
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: task-management-api-app
    ports:
      - "3333:3333"
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: 1234
      DB_DATABASE: task-management-api
    command: sh -c "npm run migration:run && npm run start:prod"

volumes:
  pgdata:
